import fs from 'fs';
import path from 'path';
import { StorageDriver } from '../../types/upload.types';

export function createLocalStorage(directory: string): StorageDriver {
  const root = path.resolve(directory);

  // Keys are generated by the server, but the resolved path is still checked so that no key can
  // ever read or write outside the upload directory
  const resolve = (key: string): string => {
    const target = path.resolve(root, key);
    if (!target.startsWith(root + path.sep)) throw new Error('[storage] key escapes the upload directory');
    return target;
  };

  return {
    name: 'local',

    async put(key, body) {
      const target = resolve(key);
      await fs.promises.mkdir(path.dirname(target), { recursive: true });
      await fs.promises.writeFile(target, body);
    },

    async get(key) {
      const target = resolve(key);
      try {
        const { size } = await fs.promises.stat(target);
        return { body: fs.createReadStream(target), size };
      } catch (err) {
        if ((err as NodeJS.ErrnoException).code === 'ENOENT') return null;
        throw err;
      }
    },

    async delete(key) {
      await fs.promises.rm(resolve(key), { force: true });
    },
  };
}
